# Avaliação Intermediária

NOME: **João Alfredo Cardoso Lamy**
E-MAIL: **joaoacl@al.insper.edu.br**

Esta é a A.I. de Álgebra Linear e Teoria da Informação de 1s2023.



INSTRUÇÕES:

1. Faça todas as questões
1. Salve o notebook
1. Envie o notebook salvo no Blackboard

IMPORTANTE:

* Você pode consultar qualquer material ou IA, mas não qualquer colega ou pessoa humana, presente ou não na prova.
* O envio da prova será fechado às 17h45. Aqueles que não enviarem o material até este horário ficarão com zero.
* A prova vale um total de 10 pontos. As questões 1, 2, 3 e 4 têm, respectivamente, pesos 1, 2, 3 e 4.
* Os conceitos F, E, D, C, B, A serão mapeados para 0, 2, 4, 6, 8 e 10.
* Para todas as questões, usaremos a rubrica que segue anexa a esta prova. Há uma rubrica para a justificativa e uma rubrica para o código. A nota da questão é a menor entre as notas da justificativa e do código.


In [110]:
import numpy as np

## Exercício 1

* Peso: 1 ponto

Dadas as matrizes:

$$
A = \begin{bmatrix} 1 & 3 &\\ 2 & 1 \end{bmatrix} \\

B = \begin{bmatrix} 2 & 3\\ 5 & 8 \end{bmatrix} \\

C = AB \\

D = BA 
$$

calcule:

$X = (ABC^{-1}BAD^{-1})^T \odot A$



In [111]:
# declaração das variáveis colocadas na questão
A = np.array([[1,3],[2,1]])
B = np.array([[2,3],[5,8]])
C = A@B
D = B@A

# definição do X, resultado de operações com matrizes que são explicitadas no enunciado da questão
X = (A@B@np.linalg.inv(C)@B@A@np.linalg.inv(D)).T * A

# print da variável X, resultado da conta que foi pedida no enunciado
X

array([[ 1.00000000e+00, -1.06581410e-15],
       [ 2.04281037e-15,  1.00000000e+00]])

# Exercício 2

* Peso: 2 pontos

Tenho uma matriz $X$ que contém todas as posições $(i,j)$ de pixels de uma figura de 600x600 pixels, sendo cada pixel armazenado em uma coluna e cada dimensão armazenada em uma linha. Qual é a matriz que permite encolher essa figura de forma que cada uma de suas dimensões seja reduzida pela metade, mas seu centro seja preservado? Se precisar, use coordenadas homogêneas!

________________________________________________________________________________________________________

A matriz que permitirá fazer todas as transformações necessárias e manter sua imagem no seu próprio centro seria uma que transladasse a imagem ao ponto de origem ($T$), aplicasse o encolhimento ($E$) e depois voltasse ela ao seu ponto original ($C$). 

$$
T = 
\begin{bmatrix}
    1 & 0 & -300 \\
    0 & 1 & -300 \\
    0 & 0 & 1
\end{bmatrix}
$$

$$
E = 
\begin{bmatrix}
    0.5 & 0 & 0 \\
    0 & 0.5 & 0 \\
    0 & 0 & 1
\end{bmatrix}
$$

$$
C = 
\begin{bmatrix}
    1 & 0 & 300 \\
    0 & 1 & 300 \\
    0 & 0 & 1
\end{bmatrix}
$$

Dessa maneira temos que $M$ (a matriz procurada) é:

$M = C E T $

Agora é só questão de calcular a matriz $M$. 

Para poder utilizar ela com $X$, precisamos de uma dimensão de 1s (uns) em uma nova linha abaixo das duas já presentes na matriz da imagem, para que a translação de pontos seja possível. Mas, já que o exercício apenas pede a matriz M, não acho importante entrar em mais detalhes sobre.

In [121]:
T = np.array([[1,0,-300],[0,1,-300],[0,0,1]])
E = np.array([[0.5,0,1],[0,0.5,0],[0,0,1]])
C = np.array([[1,0,300],[0,1,300],[0,0,1]])

M = C@E@T
M

array([[  0.5,   0. , 151. ],
       [  0. ,   0.5, 150. ],
       [  0. ,   0. ,   1. ]])

# Exercício 3

* Peso: 3 pontos

Algumas carteiras de investimento deram os seguintes retornos:

* 100 ações da empresa E1 e 200 ações da E2 deram retorno de R$100,00,
* 1000 ações da empresa E1 e 2000 ações da E2 deram retorno de R$1000,00,
* 200 ações da empresa E2 e 300 da E3 deram retorno de R$500,00 
* 400 ações da empresa E2 e 600 da E3 deram retorno de R$1000,00 
* 1000 ações da empresa E1 e 100 da E3 deram retorno de R$1500,00
* 2000 ações da empresa E1 e 200 da E3 deram retorno de R$3000,00 

*Usando estritamente formulações matriciais*, responda:
1. Qual é o retorno por ação de cada empresa?
1. Qual é o retorno de uma carteira com 100 ações da empresa E1, 200 da empresa E2 e 300 da E3?

________________________________________________________________________________________________________

Uma maneira de modelar esse problema é utilizando matrizes. 

Vamos criar uma matriz $A$, que representa o investimento feito em cada empresa (com cada carteira sendo representada por cada linha, onde cada empresa possui sua própria coluna). Escolhi modelar ela com os tópicos 1, 3 e 5 dos retornos, pois são os que nos dão os resultados mais completos para que seja possível realizar a comparação de preços (além de tornar a matriz quadrada, possibilitando realizar o processo de inversão de matrizes). Assim ficamos com a matriz:

$$
A = 
\begin{bmatrix}
    100 & 200 & 0 \\
    0 & 200 & 300 \\
    1000 & 0 & 100
\end{bmatrix}
$$


Após isso, temos a matriz de retornos finais, que nos mostra qual é o retorno total do nosso investimento nas empresas. Ela tem apenas uma coluna, e cada linha representa o retorno total de cada carteira, então, se eu investir em 100 ações da empresa E1 e 200 ações da E2 na primeira linha de $A$, a primeira linha de R será 100 (o retorno dessa carteira que foi especificado no enunciado). Assim, a matriz $R$ fica:

$$
R = 
\begin{bmatrix}
    100 \\
    500 \\
    1500
\end{bmatrix}
$$

Normalmente, temos um processo onde sabemos o retorno por ação, com a modelagem do problema sendo:

$R = AE $

A matriz $E$ é onde teríamos essas informações (retorno por ação de cada empresa), mas ela não nos foi dada, portanto, teremos que calculá-la utilizando a inversa de $A$. Ficando, assim, com a seguinte conta:

$E = A^{-1}R$

Dessa maneira, conseguimos a matriz E, e, com isso, podemos calcular o retorno de qualquer carteira.


In [113]:
# Matriz que representa o investimento nas ações das empresas
A = np.array([[100,200,0],[0,200,300],[1000,0,100]])

# Matriz que representa retorno de cada empresa
R = np.array([[100],[500],[1500]])

# Matriz que presenta o número de reais que são retornados com cada um real investido
E = np.linalg.inv(A)@R

# Resposta da pergunta 1
print(E)

[[ 1.32258065]
 [-0.16129032]
 [ 1.77419355]]


In [114]:
# Testando para ver se o resultado de "100 ações da empresa E1 e 200 ações da E2" realmente retorna 100
A1 = np.array([[100,200,0]])
print(A1@E)

print(A@E)
print(R)

[[100.]]
[[ 100.]
 [ 500.]
 [1500.]]
[[ 100]
 [ 500]
 [1500]]


In [115]:
# Respondendo a pergunta 2
pergunta2 = np.array([[100,200,300]])
pergunta2@E

array([[632.25806452]])

# Exercício 4

* Peso: 4 pontos

Uma maneira de fazer transformações em imagens é usar pontos de referência. Por exemplo, podemos definir pontos de referência em um rosto como o centro de cada um dos olhos, a ponta do nariz e o ponto inferior do queixo. Daí então, encontramos onde esses pontos estão na imagem de origem, e escolhemos (como quisermos) onde os pontos estão na imagem de destino. Encontramos a transformação linear que realiza esse mapeamento, e então aplicamos essa mesma transformação para todos os pontos da imagem, isto é:

$$
Xd = T X,
$$

onde $Xd$ é uma matriz com pontos na imagem de destino, $X$ é uma matriz com pontos na imagem de origem, e $T$ é uma transformação linear.

Num rosto, em uma imagem que está mapeada no plano cartesiano (isto é, no plano usual $x,y$ e não numa matriz de pixels), encontramos:

* O olho esquerdo em $(-2, 3)$,
* o olho direito em $(2, 3)$
* A ponta do nariz em $(0,0)$
* O ponto inferior do queixo em $(0, -3)$

O rosto foi mapeado usando uma transformação linear de forma que os pontos de referência foram deslocados para:

* O olho esquerdo em $(-6, 2)$,
* o olho direito em $(6, 1)$
* A ponta do nariz em $(3, 0)$

Usando formulações matriciais, responda: qual é a distância entre o ponto inferior do queixo e a ponta do nariz no novo mapeamento?


________________________________________________________________________________________________________

Para realizar essa conta, precisamos definir a matriz $X$ de entrada, assim como a matriz $Xd$ de saída. cada uma tem uma linha que representa os valores da coordenada x, uma outra linha para a coordenada y e uma terceira linha apenas com 1s (uns) que permite o processo de transladar.

$$
X = 
\begin{bmatrix}
    -2 & 2 & 0 \\
    3 & 3 & 0 \\
    1 & 1 & 1
\end{bmatrix}
$$

$$
Xd = 
\begin{bmatrix}
    -6 & 6 & 3 \\
    2 & 1 & 0 \\
    1 & 1 & 1
\end{bmatrix}
$$


Escolhi representar os pontos referentes ao olho esquerdo, direito e a ponta do nariz pois são os únicos que tem um correspondente direto no espaço deslocado.

Como o próprio exercício menciona, para chegar nesse novo espaço ($Xd$) temos que multiplicar a matriz $X$ por uma matriz de tranformação $T$. Nós não temos essa matriz $T$, mas conseguimos calcular ela utilizando a inversa de $X$, a conta fica:

$T = Xd X^{-1}$

Com a matriz $T$, conseguimos obter o ponto da parte inferior do queixo e, finalmente, calcular a distância entre os pontos pedidos (inferior do queixo e ponta do nariz).

In [116]:
# Array do plano cartesiano
X = np.array([[-2,3,1],[2,3,1],[0,0,1]]).T

# Array novo (array destino)
Xd = np.array([[-6,2,1],[6,1,1],[3,0,1]]).T

$Xd = TX$


$T = Xd X^{-1}$

In [117]:
# Descobrindo o array de transformação T
T = Xd@np.linalg.inv(X)

T

array([[ 3.  , -1.  ,  3.  ],
       [-0.25,  0.5 ,  0.  ],
       [ 0.  ,  0.  ,  1.  ]])

In [118]:
# Checando com o ponto do Nariz para ver se T está correto
nariz = np.array([[0,0,1]]).T

nariz = T@nariz
nariz = nariz.T

print(f"A ponta do nariz ({nariz[0][0].astype(int)},{nariz[0][1].astype(int)})")

A ponta do nariz (3,0)


In [119]:
# Ponto inferior do queixo
piq = np.array([[0,-3,1]]).T
piq = T@piq
piq = piq.T
piq

array([[ 6. , -1.5,  1. ]])

In [120]:
# Calculando a distância entre os dois pontos (ponto inferior do queixo e a ponta do nariz no novo mapeamento)

dist = np.sqrt((nariz[0][0]-piq[0][0])**2+(nariz[0][1]-piq[0][1])**2)
dist

3.3541019662496847