In [1]:
import numpy as np

## Exercício 1

Dada a equação abaixo, escolha o comando python que a implementa.
vn = a vn-1 + a2 vn-1 + a5 vn-1

In [3]:
a = 0
v = 0

v = a*v + a**2 * v + a**5 * v 

## Exercício 2

Dado o vetor v:

v = [8 8 8 6]

e o escalar a = 6.05. Calcule a * v.

In [4]:
vetor = np.array([8, 8, 8, 6])
a = 6.05

a * vetor

array([48.4, 48.4, 48.4, 36.3])

## Exercício 3

Dados os vetores v1 e v2: 

v1 = [5 5 5 3]

v2 = [4 8 6 4]

Calcule v1 + v2 =:

In [5]:
v1 = np.array([5, 5, 5, 3])
v2 = np.array([4, 8, 6, 4])

v1 + v2

array([ 9, 13, 11,  7])

## Exercício 4

Dado o vetor v:

v = [0.1 1.0 0.9 0.6]

Calcule, módulo de v:

In [3]:
v = np.array([0.1, 1.0, 0.9, 0.6])

def modulo_C(x):
    mod = np.linalg.norm(x)
    return mod

modulo_C(v)

1.47648230602334

## Exercício 5

Dados os vetores v1 e v2:

v1 = [8 6 5 5]

v2 = [4 9 5 4]

Calcule o módulo de v1 + v2 e módulo de v1 + módulo de v2

In [9]:
v1 = np.array([8, 6, 5, 5])
v2 = np.array([4, 9, 5, 4])

modulo_C((v1 + v2)), (modulo_C(v1) + modulo_C(v2))

(23.45207879911715, 23.99478883838662)

## Exercício 6

Em uma cidade, a catedral está 2km ao norte da praça.

O museu está a 10km ao oeste da catedral.

Qual a distância em linha reta entre a praça e o museu (em km)?

In [11]:
v = np.array([-10, 2])

modulo_C(v)

10.198039027185569

## Exercício 7

Um avião voa a uma velocidade de 109km/h em relação ao ar.

O vento incide perpendicularmente sobre o avião a 42km/h.

Qual a velocidade do avião em relação ao chão (em km)?

In [4]:
vel_aviao = 109
vel_vento = 42

v = [vel_aviao, vel_vento]

modulo_C(v)

116.81181447096864

## Exercício 8

Um canhão na posição (0,0) dispara um projétil em direção ao ponto (14,16).

Determine o vetor v referente ao projétil sabendo que ||v|| = 6.

É uma semelhança de triângulos, então encontrei a norma do ponto (hipotenusa) e fiz, 6/norma está para x/14 assim como y/16

In [9]:
modulo_v = 6 
ponto = np.array([14, 16])

x  = (14 * 3) / (113**0.5)
y  = (16 * 3) / (113**0.5)

x, y


(3.9510276472111086, 4.515460168241267)

## Exercício 9

Dados os 9 pontos abaixo em R^5:

v = np.array([[0.36, 0.26, 0.41, 0.38, 0.34], [0.95, 0.45, 0.55, 0.89, 0.90], [0.32, 0.48, 0.47, 0.77, 0.21], [0.97, 0.23, 0.25, 0.66, 0.53], [0.26, 0.22, 0.30, 0.29, 0.20], [0.77, 0.90, 0.63, 0.66, 0.87], [0.78, 0.13, 0.05, 0.04, 0.63], [0.93, 0.53, 0.36, 0.66, 0.76], [0.74, 0.81, 0.25, 0.18, 0.33]])

In [11]:
v = np.array([[0.36, 0.26, 0.41, 0.38, 0.34], [0.95, 0.45, 0.55, 0.89, 0.90], [0.32, 0.48, 0.47, 0.77, 0.21], [0.97, 0.23, 0.25, 0.66, 0.53], [0.26, 0.22, 0.30, 0.29, 0.20], [0.77, 0.90, 0.63, 0.66, 0.87], [0.78, 0.13, 0.05, 0.04, 0.63], [0.93, 0.53, 0.36, 0.66, 0.76], [0.74, 0.81, 0.25, 0.18, 0.33]])

menor_norma = 99999
array_menor = ''

for array in v:
    norma = modulo_C(array)

    if norma < menor_norma:
        menor_norma = norma
        array_menor = array

array_menor

array([0.26, 0.22, 0.3 , 0.29, 0.2 ])