In [1]:
import numpy as np

## Exercício 1

A matriz A apresentada abaixo pode ser utilizada para converter um pixel no formato RGB para um pixel no formato YIQ.

A = np.array( [[0.299, 0.587, 0.144], [0.5959, -0.2746, -0.3213], [0.2115, -0.5227, 0.3112]] ) 

Dada a cor (179,183,119) representada em RGB, qual a representação desta mesma cor em YIQ?

In [3]:
A = np.array( [[0.299, 0.587, 0.144], [0.5959, -0.2746, -0.3213], [0.2115, -0.5227, 0.3112]] ) 

R = np.array( [179, 183, 119] )

A @ R

array([178.078 ,  18.1796, -20.7628])

## Exercício 2

A matriz A apresentada abaixo pode ser utilizada para converter um pixel no formato RGB para um pixel em um espaço inf.

A = np.array( [ [0.084,0.059,-0.430],[0.127,-0.031,0.331],[-0.355,-0.303,-0.377] ] ) 

Um pixel de cor (1,103,73) representada em RGB foi transformado para o espaço inf, teve sua primeira componente zerada e foi transformado novamente para RGB. Qual é a cor do pixel resultante (arredondando para baixo)?


In [7]:
A = np.array( [ [0.084,0.059,-0.430],[0.127,-0.031,0.331],[-0.355,-0.303,-0.377] ] ) 

R = np.array( [1, 103, 73] )

matriz_resultante = A @ R

matriz_resultante[0] = 0

np.linalg.inv(A) @ matriz_resultante

array([107.29884918,  36.90637906,  26.02460394])

## Exercício 3

Considere o ponto x = [6, 10] no plano cartesiano e os vetores v1 e v2 abaixo.

v1 = [2, 1] 
v2 = [9, 4]

Quais seriam os valores de a, b respectivamente de modo que x = av1 + bv2?

In [11]:
v1 = np.array([2, 1])
v2 = np.array([9, 4])

x = np.array([6, 10])

v = np.stack((v1, v2), axis=0).T
v = np.linalg.inv(v)

v @ x

array([ 66., -14.])

## Exercício 4

Considere o ponto x no plano cartesiano e os vetores de base abaixo (Cada linha de v é um vetor).

import numpy as np

x = np.array([[3, 2, 6, 7, 4, 8, 6, 3, 9, 5]])

v = np.array([[2, 8, 9, 1, 7, 3, 6, 8, 3, 3], [9, 3, 6, 7, 9, 8, 7, 1, 7, 7], [8, 9, 9, 3, 7, 2, 1, 6, 9, 7], [1, 9, 8, 7, 6, 5, 7, 0, 0, 1], [5, 5, 2, 4, 2, 0, 1, 3, 2, 2], [2, 0, 9, 4, 2, 0, 2, 5, 9, 7], [1, 9, 3, 1, 1, 8, 0, 7, 2, 0], [6, 5, 5, 2, 1, 4, 4, 9, 9, 4], [9, 2, 0, 9, 1, 8, 4, 9, 6, 0], [3, 2, 5, 6, 7, 6, 7, 2, 1, 1]])

Qual o vetor equivalente a x na base v? Obs: A resposta deve estar no mesmo formato do vetor x (todos os valores em uma só linha).

In [18]:
x = np.array([[3, 2, 6, 7, 4, 8, 6, 3, 9, 5]]) 
v = np.array([[2, 8, 9, 1, 7, 3, 6, 8, 3, 3], [9, 3, 6, 7, 9, 8, 7, 1, 7, 7], [8, 9, 9, 3, 7, 2, 1, 6, 9, 7], [1, 9, 8, 7, 6, 5, 7, 0, 0, 1], [5, 5, 2, 4, 2, 0, 1, 3, 2, 2], [2, 0, 9, 4, 2, 0, 2, 5, 9, 7], [1, 9, 3, 1, 1, 8, 0, 7, 2, 0], [6, 5, 5, 2, 1, 4, 4, 9, 9, 4], [9, 2, 0, 9, 1, 8, 4, 9, 6, 0], [3, 2, 5, 6, 7, 6, 7, 2, 1, 1]])

v_transposta = v.T # está tudo em uma linha e queremos que seja coluna para conseguir fazer direito a multiplicação

np.linalg.solve(v_transposta, x.T).T # x.T é para transformar a matriz x em coluna

# também pode ser feito da seguinte maneira
v_inv = np.linalg.inv(v_transposta)

(v_inv @ x.T).T # só fizemos a transposta porque ele quer assim no prairie learn

array([[ 14.84995276,   8.35612249,   0.19625751,   8.51384352,
        -15.58396155,   0.38591093,  -5.72571857, -12.96850541,
         14.60724514, -27.58979363]])

## Exercício 5

Considere o ponto x no plano cartesiano e os vetores v2, v2 e v3 abaixo.

import numpy as np

x = np.array([[3, 1, 2]])

v1 = np.array([[6, 3, 0]])

v2 = np.array([[6, 2, 9]])

v3 = np.array([[9, 1, 6]])

Qual a matriz que leva x para o espaço determinado pelos vetores v1, v2 e v3?

In [24]:
x = np.array([[3, 1, 2]])
v1 = np.array([[6, 3, 0]])
v2 = np.array([[6, 2, 9]])
v3 = np.array([[9, 1, 6]])

B = np.vstack((v1, v2, v3)).T

np.linalg.inv(B) # qual a matriz que tenho que multiplicar os meus pontos para chegar no meu novo espaço? por isso fazemos a inversa da B

array([[ 0.01960784,  0.29411765, -0.07843137],
       [-0.11764706,  0.23529412,  0.1372549 ],
       [ 0.17647059, -0.35294118, -0.03921569]])

## Exercício 6

Calcule a matriz que levaria um ponto no espaço v para o respectivo vetor no espaço w. Ou seja, a matriz B tal que Bv = w.



In [47]:
v1 = np.array([0, 0])
v2 = np.array([0, 1])
v3 = np.array([1, 1])

v = np.vstack((v1, v2, v3)).T
v = np.vstack((v, np.ones(v.shape[1])))

w1 = np.array([2, 2])
w2 = np.array([1.3, 1.3])
w3 = np.array([1.9, 1.2])

w = np.vstack((w1, w2, w3)).T
w = np.vstack((w, np.ones(w.shape[1])))

B = v @ np.linalg.inv(w)

np.round(B, 3)

array([[ 1.429, -1.429,  0.   ],
       [-0.204, -1.224,  2.857],
       [ 0.   ,  0.   ,  1.   ]])

In [6]:
d = 2

a = 0.1
b = 1.01
objeto = np.array([[a], [b], [1]])
P = np.array([ [0,0,-d], [-1/d, 0, 0], [0, 1, 0] ])
projecao = P @ objeto

projecao[1] = projecao[2] / projecao[1]
print(projecao)

[[ -2.  ]
 [-20.2 ]
 [  1.01]]


In [4]:
d = 1

a = 13
b = 20
objeto = np.array([[a], [b], [1]])
P = np.array([ [0,0,-d], [-1/d, 0, 0], [0, 1, 0] ])
projecao = P @ objeto

projecao[1] = projecao[2] / projecao[1]
x = projecao[0]
y = projecao[1]

d_ = 4
P = np.array([ [0,0,-d_], [-1/d_, 0, 0], [0, 1, 0] ])
projecao = P @ objeto 

projecao[1] = projecao[2] / projecao[1]
x_ = projecao[0]
y_ = projecao[1]
print(x, x_, y, y_)

distancia = ((x - x_)**2 + (y - y_)**2)**0.5
distancia

[-1.] [-4.] [-1.53846154] [-6.15384615]


array([5.50470482])