# Avaliação Intermediária

Esta é a A.I. de Álgebra Linear e Teoria da Informação de 1s2023.



INSTRUÇÕES:

1. Faça todas as questões
1. Salve o notebook
1. Envie o notebook salvo no Blackboard

IMPORTANTE:

* Você pode consultar qualquer material ou IA, mas não qualquer colega ou pessoa humana, presente ou não na prova.
* O envio da prova será fechado às 17h45. Aqueles que não enviarem o material até este horário ficarão com zero.
* A prova vale um total de 10 pontos. As questões 1, 2, 3 e 4 têm, respectivamente, pesos 1, 2, 3 e 4.
* Os conceitos F, E, D, C, B, A serão mapeados para 0, 2, 4, 6, 8 e 10.
* Para todas as questões, usaremos a rubrica que segue anexa a esta prova. Há uma rubrica para a justificativa e uma rubrica para o código. A nota da questão é a menor entre as notas da justificativa e do código.


In [3]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

## Exercício 1

* Peso: 1 ponto

Dadas as matrizes:

$$
A = \begin{bmatrix} 1 & 3\\ 2 & 1 \end{bmatrix} \\

B = \begin{bmatrix} 2 & 3\\ 5 & 8 \end{bmatrix} \\

C = AB \\

D = BA 
$$

calcule:

$X = (ABC^{-1}BAD^{-1})^T \odot A$



In [5]:
A = np.array([[1, 3], [2, 1]])
B = np.array([[2, 3], [5, 8]])
C = A @ B
D = B @ A

X = (A @ B @ np.linalg.inv(C) @ B @ A @ np.linalg.inv(D)).T * A

X

array([[ 1.00000000e+00, -1.06581410e-15],
       [ 2.04281037e-15,  1.00000000e+00]])

Foi realizado multiplicações matriciais utilizando o operador @ e depois o operador *, que realiza uma multiplicação ponto a ponto.

# Exercício 2

* Peso: 2 pontos

Tenho uma matriz $X$ que contém todas as posições $(i,j)$ de pixels de uma figura de 600x600 pixels, sendo cada pixel armazenado em uma coluna e cada dimensão armazenada em uma linha. Qual é a matriz que permite encolher essa figura de forma que cada uma de suas dimensões seja reduzida pela metade, mas seu centro seja preservado? Se precisar, use coordenadas homogêneas!

________________________________________________________________________________________________________

In [11]:
def criar_indices(min_i, max_i, min_j, max_j):
    import itertools
    L = list(itertools.product(range(min_i, max_i), range(min_j, max_j)))
    idx_i = np.array([e[0] for e in L])
    idx_j = np.array([e[1] for e in L])
    idx = np.vstack( (idx_i, idx_j) )
    return idx

In [17]:
image = mpimg.imread("imagem.jpeg")
image_ = np.zeros_like(image)

# resizing a imagem 
matriz_final = criar_indices(0, image.shape[0], 0, image.shape[1])
matriz_final = np.vstack((matriz_final, np.ones(matriz_final.shape[1])))
matriz_translacao = np.array([[1, 0, -(image.shape[0]/2)], [0, 1, -(image.shape[1]/2)], [0, 0, 1]])
matriz_reducao_x = np.array([[0.5, 0, 0], [0, 0.5, 0], [0, 0, 1]])

transformacao = np.linalg.inv(matriz_translacao) @ matriz_reducao_x @ matriz_translacao

indices_original = np.linalg.inv(transformacao) @ matriz_final
indices_original = indices_original.astype(int)
matriz_final = matriz_final.astype(int)

image_[matriz_final[0,:], matriz_final[1,:], :] = image[indices_original[0,:], indices_original[1,:], :]

plt.figure(figsize=(10,10))
plt.subplot(1,2,1)
plt.imshow(image)
plt.title('Origem')
plt.subplot(1,2,2)
plt.imshow(image_)
plt.title('Destino')
plt.show()

IndexError: index 768 is out of bounds for axis 0 with size 768

Para realizar uma redução de uma imagem mantendo seu centro preservado, primeiro temos que transladar ela para o ponto de origem, realizar a redução e depois transladar ela novamente para o centro, da seguinte forma:

$$
T = 
\begin{bmatrix}
    1 & 0 & -300 \\
    0 & 1 & -300 \\
    0 & 0 & 1
\end{bmatrix}
$$

$$
R = 
\begin{bmatrix}
    0.5 & 0 & 0 \\
    0 & 0.5 & 0 \\
    0 & 0 & 1
\end{bmatrix}
$$

Para realizar a translação da matriz novamente para seu ponto de origem, basta apenas multiplicar pelo inverso da matriz de translação original, portanto temos:

matriz_final = np.linalg.inv(T) @ R @ T 

Dessa forma, temos a matriz de redução. 

# Exercício 3

* Peso: 3 pontos

Algumas carteiras de investimento deram os seguintes retornos:

* 100 ações da empresa E1 e 200 ações da E2 deram retorno de R$100,00,
* 1000 ações da empresa E1 e 2000 ações da E2 deram retorno de R$1000,00,
* 200 ações da empresa E2 e 300 da E3 deram retorno de R$500,00 
* 400 ações da empresa E2 e 600 da E3 deram retorno de R$1000,00 
* 1000 ações da empresa E1 e 100 da E3 deram retorno de R$1500,00
* 2000 ações da empresa E1 e 200 da E3 deram retorno de R$3000,00 

*Usando estritamente formulações matriciais*, responda:
1. Qual é o retorno por ação de cada empresa?
1. Qual é o retorno de uma carteira com 100 ações da empresa E1, 200 da empresa E2 e 300 da E3?

________________________________________________________________________________________________________

In [43]:
acoes = np.array([[100, 200, 0], [0, 200, 300], [1000, 0, 100]])
retorno = np.array([[100], [500], [1500]])

retorno_por_acao = np.linalg.solve(acoes, retorno)

carteira = np.array([100, 200, 300])

retorno_carteira = carteira @ retorno_por_acao

retorno_por_acao, retorno_carteira

(array([[ 1.32258065],
        [-0.16129032],
        [ 1.77419355]]),
 array([632.25806452]))

Para realizar o retorno por ação, foi necessário escolher uma matriz que não fosse singular, portanto que tivesse combinações diferentes que me trouxessem o resultado. Quando fiz com todas as carteiras, deu um problema de matriz quadrada, e ai depois quando escolhi as tres primeiras deu um problema de matriz singular, portanto a escolha das carteiras utilizadas importa. Levando isso em consideração, eu escolhi as carteiras: 1, 3 e 5, isso porque elas combinam E1 com E2, E2 com E3 e E1 com E3, deixando viável para que encontremos o retorno de cada ação. Para tanto, realizei a multipliação matricial, utilizando o np.linalg.solve, que nada mais é que a multipliação do inverso da matriz de ações pela de retornos. Após isso, o que foi feito para descobrir o retorno das empresas, foi apenas multiplicar o retorno de cada ação pela carteira disponibilizada. 

# Exercício 4

* Peso: 4 pontos

Uma maneira de fazer transformações em imagens é usar pontos de referência. Por exemplo, podemos definir pontos de referência em um rosto como o centro de cada um dos olhos, a ponta do nariz e o ponto inferior do queixo. Daí então, encontramos onde esses pontos estão na imagem de origem, e escolhemos (como quisermos) onde os pontos estão na imagem de destino. Encontramos a transformação linear que realiza esse mapeamento, e então aplicamos essa mesma transformação para todos os pontos da imagem, isto é:

$$
Xd = T X,
$$

onde $Xd$ é uma matriz com pontos na imagem de destino, $X$ é uma matriz com pontos na imagem de origem, e $T$ é uma transformação linear.

Num rosto, em uma imagem que está mapeada no plano cartesiano (isto é, no plano usual $x,y$ e não numa matriz de pixels), encontramos:

* O olho esquerdo em $(-2, 3)$,
* o olho direito em $(2, 3)$
* A ponta do nariz em $(0,0)$
* O ponto inferior do queixo em $(0, -3)$

O rosto foi mapeado usando uma transformação linear de forma que os pontos de referência foram deslocados para:

* O olho esquerdo em $(-6, 2)$,
* o olho direito em $(6, 1)$
* A ponta do nariz em $(3, 0)$

Usando formulações matriciais, responda: qual é a distância entre o ponto inferior do queixo e a ponta do nariz no novo mapeamento?


________________________________________________________________________________________________________

In [47]:
pts_origem = np.array([[-2, 3], [2, 3], [0, 0]])
pts_destino = np.array([[-6, 2], [6, 1], [3, 0]])

v = np.vstack((pts_origem.T, np.ones(pts_origem.shape[0])))
w = np.vstack((pts_destino.T, np.ones(pts_destino.shape[0])))
B = w @ np.linalg.inv(v)

ponto_inf_queixo_novo = B @ np.array([0, -3, 1])

# distância da ponta do nariz ao ponto inferior do queixo
dist_ponto_inf_nariz_novo = np.linalg.norm(np.array([3, 0, 1]) - ponto_inf_queixo_novo)

ponto_inf_queixo_novo, dist_ponto_inf_nariz_novo

(array([ 6. , -1.5,  1. ]), 3.3541019662496847)

Para encontrar a matriz B, foi necessário utilizarmos os pontos origem e os de destino que tínhamos em ambos, sendo eles o olho esquerdo, direito e a ponta do nariz. Fazendo uso desses pontos, pude realizar a operação para descobrir a matriz B que multiplica os pontos de origem para chegar na matriz dos pontos de destino, como foi identificado. Sendo assim, após descobrir a matriz que multiplica, para descobrir o ponto novo do queixo, bastou multiplicar a matriz B pelos pontos de origem do queixo, e para descobrir a distância, utilizei a norma do vetor, calculando pelo np.linalg.norm, que devolve a distância entre dois vetores.